apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-eta-deploy
  labels:
    app: insurance-eta-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insurance-eta-app
  template:
    metadata:
      labels:
        app: insurance-eta-app
    spec:
      containers:
      - name: insurance-eta-container
        image: mrunalnimbalkr/insurance-eta-app:latest
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: insurance-eta-np-service
  labels:
    app: insurance-eta-app
spec:
  selector:
    app: insurance-eta-app

  type: NodePort
  ports:
  - nodePort: 31034
    port: 8081
    targetPort: 8081
